export const ProductModel = {
  picture: null,
  name: '',
  category: '',
  description: '',
  size: '',
  products: [],
  totalQuantity: '',
  commission: '',
  price: '',
  additionalFee: '',
  shippingFee: '',
  // totalPrice: '',
  user: '',
};
