export const ProductModel = {
  picture: null,
  name: '',
  category: '',
  description: '',
  size: '',
  products: [],
  totalQuantity: '',
  price: '',
  additionalFee: '',
  shippingFee: '',
  user: '',
  bazlFee: '',
  influencerFee: '',
  bazlGain: '',
  influencerGain: '',
};
